#!/usr/bin/env python3
import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

# TODO
def main():
    
    if len(sys.argv) != 2:
        # accepts one and only one command-line argument, the screen name for a user on Twitter,
        sys.exit("must have twitter handle as cmd line arg")
    username = sys.argv[1]
    
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    # instantiate analyzer
    # queries Twitter’s API for a user’s most recent 50 tweets,
    tweets = get_user_timeline(username)
    # analyzes the sentiment of each of those tweets, and
    for tweet in tweets:
        analyzer = Analyzer(positives, negatives)
        score = analyzer.analyze(tweet)
        if (score > 0.0):
            print("{} {}".format(colored(score, "green"), colored(tweet, "green")))
        elif (score < 0.0):
            print("{} {}".format(colored(score, "red"), colored(tweet, "red")))
        else:
            print("{} {}".format(colored(score, "yellow"), colored(tweet, "yellow")))
    
    # outputs each tweet’s score and text, colored in green if positive, red if negative, and yellow otherwise.
if __name__ == "__main__":
    main()